### ISSUE TITLE
Facing issue at initial connection AARQ

### ISSUE THREAD

**Issue by ngoyal16** [nyotiemon/gosem#4]
We are facing issue while using the package

https://github.com/Circutor/gosem

AARQ initial connect fails

**Comment by ngoyal16** [comment]
@jduranf

**Comment by nyotiemon** [comment]
Well unfortunately I didnt make the AARQ to connect to the device in this work. Only the en/decoder of the data transfer

**Comment by jduranf** [comment]
@ngoyal16 currently we are working to have a functional DLMS client using golang, based in @nyotiemon work. Currently it's possible to associate and get some values using TCP + Wrapper, you have a working [example](https://github.com/Circutor/gosem/blob/main/example/main.go). If you have any problem, or you want to collaborate, please leave a more explicit comment in the [issues section](https://github.com/Circutor/gosem/issues).

**Comment by ngoyal16** [comment]
@jduranf @nyotiemon https://github.com/Circutor/gosem/issues/1
